name: Deployment Pipeline
on:
  push:
    branches: [main]

jobs: 
  simple-deployment-pipeline:
    runs-on: ubantu-latest
    steps:
      - uses: actions/checkout@v3
        name: test
      - run: echo "Hi"
      
