name: Deployment Pipeline
on: 
  push:
    branches:
      - master
jobs: 
  simple-deployment-pipeline:
    runs-on: ubantu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: Install dependencies 
        run: npm install  
      - name: Check style
        run: npm run eslintrc
